# Generated by Django 4.1.3 on 2022-11-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Comand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percents', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_at', models.DateField(auto_now=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Modificado em')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
